### ISSUE TITLE
Fail to build on Ubuntu 16.04 LTS 

### ISSUE THREAD

**Issue by rpgallan** [rpgallan/diamantinacoin#3]
Ubuntu 16.04 LTS
Memory: 3,8 GiB
Processor: Intel® Core™ i3-2120 CPU @ 3.30GHz × 4
Graphics: GeForce GT 710/PCIe/SSE2
OS type: 64 bits

Error on build:
[ 62%] Linking CXX executable connectivity_tool
/usr/bin/ld: StreamTools.cpp.o: plugin needed to handle lto object
/tmp/ccV0fI9r.ltrans1.ltrans.o: In function std::_Function_handler<void (), handle_request_stat(boost::program_options::variables_map&, unsigned long)::{lambda()#4}>::_M_invoke(std::_Any_data const&) [clone .lto_priv.444]': <artificial>:(.text+0x1df3): undefined reference toCommon::write(Common::IOutputStream&, void const*, unsigned long)'
:(.text+0x1e26): undefined reference to Common::write(Common::IOutputStream&, void const*, unsigned long)' <artificial>:(.text+0x1f7b): undefined reference toCommon::write(Common::IOutputStream&, void const*, unsigned long)'
:(.text+0x1fbe): undefined reference to Common::write(Common::IOutputStream&, void const*, unsigned long)' /tmp/ccV0fI9r.ltrans1.ltrans.o: In functionstd::_Function_handler<void (), handle_request_stat(boost::program_options::variables_map&, unsigned long)::{lambda()#3}>::_M_invoke(std::_Any_data const&) [clone .lto_priv.446]':
:(.text+0x2320): undefined reference to Common::write(Common::IOutputStream&, void const*, unsigned long)' /tmp/ccV0fI9r.ltrans1.ltrans.o:<artificial>:(.text+0x234d): more undefined references toCommon::write(Common::IOutputStream&, void const*, unsigned long)' follow
/tmp/ccV0fI9r.ltrans25.ltrans.o: In function CryptoNote::KVBinaryInputStreamSerializer::KVBinaryInputStreamSerializer(Common::IInputStream&)': <artificial>:(.text+0x1238): undefined reference toCommon::read(Common::IInputStream&, void*, unsigned long)'
/tmp/ccV0fI9r.ltrans26.ltrans.o: In function CryptoNote::KVBinaryOutputStreamSerializer::checkArrayPreamble(unsigned char)': <artificial>:(.text+0x7b): undefined reference toCommon::write(Common::IOutputStream&, void const*, unsigned long)'
/tmp/ccV0fI9r.ltrans26.ltrans.o: In function CryptoNote::KVBinaryOutputStreamSerializer::writeElementPrefix(unsigned char, Common::StringView)': <artificial>:(.text+0x111): undefined reference toCommon::write(Common::IOutputStream&, void const*, unsigned long)'
/tmp/ccV0fI9r.ltrans26.ltrans.o: In function (anonymous namespace)::loadSection(Common::IInputStream&) [clone .lto_priv.380]': <artificial>:(.text+0x16e): undefined reference toCommon::read(Common::IInputStream&, unsigned char&)'
:(.text+0x1a9): undefined reference to Common::read(Common::IInputStream&, unsigned char&)' <artificial>:(.text+0x20e): undefined reference toCommon::read(Common::IInputStream&, void*, unsigned long)'
:(.text+0x26a): undefined reference to Common::read(Common::IInputStream&, void*, unsigned long)' <artificial>:(.text+0x295): undefined reference toCommon::read(Common::IInputStream&, void*, unsigned long)'
:(.text+0x2d0): undefined reference to Common::read(Common::IInputStream&, unsigned char&)' <artificial>:(.text+0x309): undefined reference toCommon::read(Common::IInputStream&, unsigned char&)'
/tmp/ccV0fI9r.ltrans26.ltrans.o: In function (anonymous namespace)::loadValue(Common::IInputStream&, unsigned char)': <artificial>:(.text+0x6b7): undefined reference toCommon::read(Common::IInputStream&, unsigned char&)'
:(.text+0x724): undefined reference to Common::read(Common::IInputStream&, void*, unsigned long)' <artificial>:(.text+0x764): undefined reference toCommon::read(Common::IInputStream&, void*, unsigned long)'
:(.text+0x794): undefined reference to Common::read(Common::IInputStream&, void*, unsigned long)' <artificial>:(.text+0x7c4): undefined reference toCommon::read(Common::IInputStream&, void*, unsigned long)'
:(.text+0x804): undefined reference to Common::read(Common::IInputStream&, void*, unsigned long)' /tmp/ccV0fI9r.ltrans26.ltrans.o:<artificial>:(.text+0x824): more undefined references toCommon::read(Common::IInputStream&, void*, unsigned long)' follow
/tmp/ccV0fI9r.ltrans26.ltrans.o: In function (anonymous namespace)::loadValue(Common::IInputStream&, unsigned char)': <artificial>:(.text+0x86c): undefined reference toCommon::read(Common::IInputStream&, unsigned char&)'
:(.text+0x8a7): undefined reference to Common::read(Common::IInputStream&, unsigned char&)' <artificial>:(.text+0x949): undefined reference toCommon::read(Common::IInputStream&, unsigned char&)'
:(.text+0x984): undefined reference to Common::read(Common::IInputStream&, void*, unsigned long)' <artificial>:(.text+0x9b4): undefined reference toCommon::read(Common::IInputStream&, void*, unsigned long)'
:(.text+0x9e4): undefined reference to Common::read(Common::IInputStream&, void*, unsigned long)' <artificial>:(.text+0xa69): undefined reference toCommon::read(Common::IInputStream&, unsigned char&)'
:(.text+0xa9c): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/ConnectivityTool.dir/build.make:113: recipe for target 'src/connectivity_tool' failed
make[3]: *** [src/connectivity_tool] Error 1
make[3]: Leaving directory '/home/rpg/diamantinacoin/build/release'
CMakeFiles/Makefile2:955: recipe for target 'src/CMakeFiles/ConnectivityTool.dir/all' failed
make[2]: *** [src/CMakeFiles/ConnectivityTool.dir/all] Error 2
make[2]: Leaving directory '/home/rpg/diamantinacoin/build/release'
Makefile:94: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/rpg/diamantinacoin/build/release'
Makefile:20: recipe for target 'build-release' failed
make: *** [build-release] Error 2
