### ISSUE TITLE
Fail to build on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by rpgallan** [rpgallan/diamantinacoin#1]
Ubuntu 16.04 LTS

ERROR:

Scanning dependencies of target ConnectivityTool
[ 62%] Building CXX object src/CMakeFiles/ConnectivityTool.dir/ConnectivityTool/ConnectivityTool.cpp.o
[ 62%] Linking CXX executable connectivity_tool
libSerialization.a(KVBinaryOutputStreamSerializer.cpp.o): In function `packVarint<long unsigned int>':
/home/rpg/diamantinacoin/src/Serialization/KVBinaryOutputStreamSerializer.cpp:26: undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
libSerialization.a(KVBinaryOutputStreamSerializer.cpp.o): In function `packVarint<short unsigned int>':
/home/rpg/diamantinacoin/src/Serialization/KVBinaryOutputStreamSerializer.cpp:26: undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
libSerialization.a(KVBinaryOutputStreamSerializer.cpp.o): In function `packVarint<unsigned char>':
/home/rpg/diamantinacoin/src/Serialization/KVBinaryOutputStreamSerializer.cpp:26: undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
libSerialization.a(KVBinaryOutputStreamSerializer.cpp.o): In function `packVarint<unsigned int>':
/home/rpg/diamantinacoin/src/Serialization/KVBinaryOutputStreamSerializer.cpp:26: undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
libSerialization.a(KVBinaryOutputStreamSerializer.cpp.o): In function `(anonymous namespace)::writeElementName(Common::IOutputStream&, Common::StringView) [clone .constprop.65]':
/home/rpg/diamantinacoin/src/Serialization/KVBinaryOutputStreamSerializer.cpp:36: undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
libSerialization.a(KVBinaryOutputStreamSerializer.cpp.o):/home/rpg/diamantinacoin/src/Serialization/KVBinaryOutputStreamSerializer.cpp:37: more undefined references to `Common::write(Common::IOutputStream&, void const*, unsigned long)' follow
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `unsigned char Common::read<unsigned char>(Common::IInputStream&)':
/home/rpg/diamantinacoin/src/Common/StreamTools.h:47: undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
/home/rpg/diamantinacoin/src/Common/StreamTools.h:47: undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `readPod<unsigned char>':
/home/rpg/diamantinacoin/src/Serialization/KVBinaryInputStreamSerializer.cpp:22: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
/home/rpg/diamantinacoin/src/Serialization/KVBinaryInputStreamSerializer.cpp:22: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `readName':
/home/rpg/diamantinacoin/src/Serialization/KVBinaryInputStreamSerializer.cpp:87: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `readPod<long int>':
/home/rpg/diamantinacoin/src/Serialization/KVBinaryInputStreamSerializer.cpp:22: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `readPod<int>':
/home/rpg/diamantinacoin/src/Serialization/KVBinaryInputStreamSerializer.cpp:22: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o):/home/rpg/diamantinacoin/src/Serialization/KVBinaryInputStreamSerializer.cpp:22: more undefined references to `Common::read(Common::IInputStream&, void*, unsigned long)' follow
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `unsigned char Common::read<unsigned char>(Common::IInputStream&)':
/home/rpg/diamantinacoin/src/Common/StreamTools.h:47: undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `readString':
/home/rpg/diamantinacoin/src/Serialization/KVBinaryInputStreamSerializer.cpp:74: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `readPod<CryptoNote::KVBinaryStorageBlockHeader>':
/home/rpg/diamantinacoin/src/Serialization/KVBinaryInputStreamSerializer.cpp:22: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/ConnectivityTool.dir/build.make:113: recipe for target 'src/connectivity_tool' failed
make[2]: *** [src/connectivity_tool] Error 1
CMakeFiles/Makefile2:955: recipe for target 'src/CMakeFiles/ConnectivityTool.dir/all' failed
make[1]: *** [src/CMakeFiles/ConnectivityTool.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
