### ISSUE TITLE
Fail to build on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by rpgallan** [rpgallan/diamantinacoin#1]
Ubuntu 14.04 LTS
Memory: 3,5 GiB
Processor: Intel® Celeron(R) CPU G1820 @ 2.70GHz × 2 
Graphics: Intel® Haswell Desktop 
OS type: 64 bits
Up to Date

Problem on build:
Scanning dependencies of target ConnectivityTool
make[3]: Leaving directory '/home/rpg/diamantinacoin/build/release'
make[3]: Entering directory '/home/rpg/diamantinacoin/build/release'
[ 62%] Building CXX object src/CMakeFiles/ConnectivityTool.dir/ConnectivityTool/ConnectivityTool.cpp.o
[ 62%] Linking CXX executable connectivity_tool
/usr/bin/ld: StreamTools.cpp.o: plugin needed to handle lto object
/tmp/ccKBoaaU.ltrans1.ltrans.o: In function `std::_Function_handler<void (), handle_request_stat(boost::program_options::variables_map&, unsigned long)::{lambda()#4}>::_M_invoke(std::_Any_data const&) [clone .lto_priv.449]':
<artificial>:(.text+0x1da3): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
<artificial>:(.text+0x1dd6): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
<artificial>:(.text+0x1f2b): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
<artificial>:(.text+0x1f6e): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
/tmp/ccKBoaaU.ltrans1.ltrans.o: In function `std::_Function_handler<void (), handle_request_stat(boost::program_options::variables_map&, unsigned long)::{lambda()#3}>::_M_invoke(std::_Any_data const&) [clone .lto_priv.451]':
<artificial>:(.text+0x22a0): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
/tmp/ccKBoaaU.ltrans1.ltrans.o:<artificial>:(.text+0x22cd): more undefined references to `Common::write(Common::IOutputStream&, void const*, unsigned long)' follow
/tmp/ccKBoaaU.ltrans22.ltrans.o: In function `CryptoNote::KVBinaryInputStreamSerializer::KVBinaryInputStreamSerializer(Common::IInputStream&)':
<artificial>:(.text+0xb98): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
/tmp/ccKBoaaU.ltrans27.ltrans.o: In function `CryptoNote::KVBinaryOutputStreamSerializer::checkArrayPreamble(unsigned char)':
<artificial>:(.text+0x7b): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
/tmp/ccKBoaaU.ltrans27.ltrans.o: In function `CryptoNote::KVBinaryOutputStreamSerializer::writeElementPrefix(unsigned char, Common::StringView)':
<artificial>:(.text+0x111): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
/tmp/ccKBoaaU.ltrans27.ltrans.o: In function `(anonymous namespace)::loadSection(Common::IInputStream&) [clone .lto_priv.388]':
<artificial>:(.text+0x16e): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
<artificial>:(.text+0x1a9): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
<artificial>:(.text+0x20e): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
<artificial>:(.text+0x26a): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
<artificial>:(.text+0x295): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
<artificial>:(.text+0x2d0): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
<artificial>:(.text+0x309): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
/tmp/ccKBoaaU.ltrans27.ltrans.o: In function `(anonymous namespace)::loadValue(Common::IInputStream&, unsigned char)':
<artificial>:(.text+0x687): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
<artificial>:(.text+0x6f4): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
<artificial>:(.text+0x734): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
<artificial>:(.text+0x764): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
<artificial>:(.text+0x794): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
<artificial>:(.text+0x7c4): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
/tmp/ccKBoaaU.ltrans27.ltrans.o:<artificial>:(.text+0x7e4): more undefined references to `Common::read(Common::IInputStream&, void*, unsigned long)' follow
/tmp/ccKBoaaU.ltrans27.ltrans.o: In function `(anonymous namespace)::loadValue(Common::IInputStream&, unsigned char)':
<artificial>:(.text+0x8c9): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
<artificial>:(.text+0x8fc): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
<artificial>:(.text+0x937): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
<artificial>:(.text+0xa39): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
<artificial>:(.text+0xa6c): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/ConnectivityTool.dir/build.make:113: recipe for target 'src/connectivity_tool' failed
make[3]: *** [src/connectivity_tool] Error 1
make[3]: Leaving directory '/home/rpg/diamantinacoin/build/release'
CMakeFiles/Makefile2:955: recipe for target 'src/CMakeFiles/ConnectivityTool.dir/all' failed
make[2]: *** [src/CMakeFiles/ConnectivityTool.dir/all] Error 2
make[2]: Leaving directory '/home/rpg/diamantinacoin/build/release'
Makefile:94: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/rpg/diamantinacoin/build/release'
Makefile:20: recipe for target 'build-release' failed
make: *** [build-release] Error 2
